# Generated by Django 5.2.3 on 2025-06-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_order_billing_address_order_shipping_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='name',
            new_name='category_name',
        ),
    ]
